## Curso: Análise e Desenvolvimento de Sistemas

## Disciplina:  DISRUPTIVE ARCHITECTURES: IOT, IA & GENERATIVE AI

## Turmas: 2TDS (1o semestre de 2026)

## Professor: André Tritiack

In [31]:
# Importações
import pandas as pd
from sklearn.model_selection import train_test_split

# Algoritimos de classificação
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# Conversão
from sklearn.preprocessing import LabelEncoder

# Métricas de avaliação:
# Matriz de confusão
from sklearn.metrics import confusion_matrix

# Acurácia
from sklearn.metrics import accuracy_score

# Precisão do modelo
from sklearn.metrics import precision_score

# Recall do modelo
from sklearn.metrics import recall_score

# F1-score do modelo
from sklearn.metrics import f1_score

----------------------

## **Diagnóstico médico: Problemas Ortopédicos na Coluna Vertebral**

Esse dataset contém dados sobre problemas ortopédicos na coluna vertebral, diagnosticados no Centre Médico-Chirurgical de Réadaptation des Massues, em Lyon, France. Contém 6 atributos biomecânicos para 310 entradas anonimizadas, sendo 100 de pacientes considerados sem problemas (Normal - NO), 60 de pacientes com Hérnia de Disco (Disk Hernia - DH) e 150 de pacientes com Espondilolistese (Spondylolisthesis - SL).

Maiores informações disponíveis em https://www.openml.org/d/1523

Escolha dois algoritmos para treinar seus modelos de classificação.

Opções: KNN, Random Forest, Decision Tree, Logistic Regression, SVM

In [5]:
# Criação do dataframe
df1 = pd.read_csv('/content/questao_01.csv')

In [7]:
# Visualize os primeiros registros
df1.head()

,Unnamed: 0,V1,V2,V3,V4,V5,V6,diagnostic
0,0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,Disk Hernia
1,1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,Disk Hernia
2,2,68.832021,22.218482,50.092194,46.613539,105.985136,-3.530317,Disk Hernia
3,3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,Disk Hernia
4,4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,Disk Hernia

In [9]:
# Visualize o tamanho do dataframe
df1.shape

(310, 8)

In [24]:
# Mostre uma tabela com as informações dos atributos (formato dos dados)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  310 non-null    int64
 1   V1          310 non-null    float64
 2   V2          310 non-null    float64
 3   V3          310 non-null    float64
 4   V4          310 non-null    float64
 5   V5          310 non-null    float64
 6   V6          310 non-null    float64
 7   diagnostic  310 non-null    object
dtypes: float64(6), int64(1), object(1)
memory usage: 19.5+ KB

In [25]:
# Mostre uma tabela com as estatísticas descritivas dos atributos
df1.describe()

,Unnamed: 0,V1,V2,V3,V4,V5,V6
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,154.500000,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694
std,89.633513,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027
min,0.000000,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179
25%,77.250000,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727
50%,154.500000,58.691038,16.357689,49.562398,42.404912,118.268178,11.767933
75%,231.750000,72.877696,22.120395,63.000000,52.695889,125.467675,41.287352
max,309.000000,129.834041,49.431864,125.742386,121.429566,163.071041,418.543082

In [32]:
# Conversão de dados categóricos em numéricos (coluna "diagnostic")
le = LabelEncoder()

df1["diagnostic"] = le.fit_transform(df1["diagnostic"])

print(df1["diagnostic"].value_counts())

diagnostic
2    150
1    100
0     60
Name: count, dtype: int64

In [36]:
# Visualização dos dados da coluna "diagnostic" após a transformação
df1['diagnostic'].value_counts()

diagnostic
2    150
1    100
0     60
Name: count, dtype: int64

In [37]:
# Verificação da distribuição das categorias
df1['diagnostic'].unique()

array([0, 2, 1])

In [ ]:
# Contabilizando quantidade de valores
df1['diagnostic'].value_counts()

Crie as variáveis X e y.

X deve ser um dataframe que contenha os dados dos seis atributos referentes aos biomarcadores (V1 a V6).

y deve ser um array com os dados da coluna "diagnostic".

In [22]:
# Coloque aqui o seu código para a variável X
# X = df1.drop(columns=['Unnamed: 0','diagnostic'])
X = df1[['V1', 'V2', 'V3', 'V4', 'V5', 'V6']]
X.head()

          V1         V2         V3         V4          V5         V6
0  63.027818  22.552586  39.609117  40.475232   98.672917  -0.254400
1  39.056951  10.060991  25.015378  28.995960  114.405425   4.564259
2  68.832021  22.218482  50.092194  46.613539  105.985136  -3.530317
3  69.297008  24.652878  44.311238  44.644130  101.868495  11.211523
4  49.712859   9.652075  28.317406  40.060784  108.168725   7.918501

In [34]:
# Coloque aqui o seu código para a variável y
y = df1['diagnostic']

diagnostic
2    150
1    100
0     60
Name: count, dtype: int64

In [15]:
# Visualize os primeiros registros do dataframe X
df1.columns

Index(['Unnamed: 0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'diagnostic'], dtype='object')

In [38]:
# Visualize X como um array Numpy (values)
X.values

array([[ 63.027818,  22.552586,  39.609117,  40.475232,  98.672917,
         -0.2544  ],
       [ 39.056951,  10.060991,  25.015378,  28.99596 , 114.405425,
          4.564259],
       [ 68.832021,  22.218482,  50.092194,  46.613539, 105.985136,
         -3.530317],
       ...,
       [ 61.446597,  22.694968,  46.170347,  38.751628, 125.670725,
         -2.70788 ],
       [ 45.252792,   8.693157,  41.583126,  36.559635, 118.545842,
          0.21475 ],
       [ 33.841641,   5.073991,  36.641233,  28.767649, 123.945244,
         -0.199249]])

In [39]:
# Visualize y como um array Numpy
y.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

Abaixo, separe 70% dos dados para treinamento e 30% para teste.

Utilize os nomes X_train, X_test, y_train e y_test

In [40]:
# Separação de dados de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
# Crie a instância do primeiro modelo:

In [ ]:
# Treine o primeiro modelo:

In [ ]:
# Gere o array de previsões "y_predict_1":

In [ ]:
# Crie a instância do segundo modelo:

In [ ]:
# Visualize y_predict_1:

In [ ]:
# Treine o segundo modelo:

In [ ]:
# Gere o array de previsões "y_predict_2":

In [ ]:
# Visualize y_predict_2:

In [ ]:
# Apresente a acurácia do primeiro modelo.

In [ ]:
# Apresente a acurácia do segundo modelo.

## **Diagnóstico médico: Diabetes no povo Pima**

## Você pode construir um modelo de aprendizado de máquina para prever com precisão se os pacientes no conjunto de dados têm diabetes ou não?

Esse dataset contém dados sobre incidência de diabetes em mulheres do Povo Pima (índios nativos norte americanos originários do atual Estado do Arizona). Contém 8 atributos biomédicos para 768 entradas anonimizadas, sendo 500 testados negativo para diabetes e 268 testados positivo para diabetes.

Faça o download do dataset:

https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database


Utilize as técnicas e a mesma sequência e estrutura da primeira parte para desenvolver sua solução.

Escolha o algoritmo de sua preferência.