In [13]:
# Importando bibliotecas
import pandas as pd
from sklearn.model_selection import train_test_split # Para separação de treino e teste

In [2]:
# Criar um dataframe "dados" a partir do arquivo SAMPLE_ENERGY_DATA.csv
dados = pd.read_csv('/content/SAMPLE_ENERGY_DATA.csv')

In [ ]:
type(dados)

# Análise exploratória

In [4]:
# Dimensões da dataframe
# Linhas  ===> Registros
# Colunas ===> Atributos (FEATURES)
dados.shape
print(f'Total de Registros: {dados.shape[0]}')
print(f'Total de Atributos: {dados.shape[1]}')

Total de Registros: 61479
Total de Atributos: 9

In [5]:
# Informações dos atributos
# Formato dos dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61479 entries, 0 to 61478
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   61479 non-null  object
 1   Time                   61479 non-null  object
 2   Global_active_power    61479 non-null  float64
 3   Global_reactive_power  61479 non-null  float64
 4   Voltage                61479 non-null  float64
 5   Global_intensity       61479 non-null  float64
 6   Sub_metering_1         61479 non-null  int64
 7   Sub_metering_2         61479 non-null  int64
 8   Sub_metering_3         61479 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 4.2+ MB

In [6]:
# Estatísticas descritivas dos atributos numéricos
# min, max, media, desvio padrão
dados.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,61479.000000,61479.000000,61479.000000,61479.000000,61479.000000,61479.000000,61479.000000
mean,1.094093,0.124659,240.823839,4.637222,1.146424,1.284162,6.511118
std,1.059194,0.112706,3.240829,4.449635,6.229518,5.786388,8.456715
min,0.076000,0.000000,225.740000,0.200000,0.000000,0.000000,0.000000
25%,0.310000,0.048000,238.990000,1.400000,0.000000,0.000000,0.000000
50%,0.610000,0.100000,241.000000,2.600000,0.000000,0.000000,1.000000
75%,1.530000,0.196000,242.870000,6.400000,0.000000,1.000000,17.000000
max,10.290000,1.078000,253.320000,44.600000,80.000000,77.000000,31.000000

# Exemplo:
Criar um modelo preditivo para previsão da potência ativa (Global_active_power) usando como dados de entrada um dataframe com os atributos: 'Voltage', 'Global_intensity', 'Sub_metering_1'

In [11]:
# Dados de entrada ===> Features:
# X ===> dataframe
X = dados[['Voltage', 'Global_intensity', 'Sub_metering_1']]
X.head()

   Voltage  Global_intensity  Sub_metering_1
0   240.17               6.4               0
1   245.50               1.8               0
2   239.85               3.0               0
3   235.72               1.4               0
4   243.95               5.6               0

In [12]:
# Dados de saída ===> Target:
# y ===> Array
y = dados['Global_active_power']
y.head()

0    1.502
1    0.374
2    0.620
3    0.280
4    1.372
Name: Global_active_power, dtype: float64

In [14]:
# Separar os dados de X e y em treinamento e teste
# Treino ===> 70%
# Teste  ===> 30%
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3)